[package]
name = "rs-google-photos-sync"
version = "0.1.0"
authors = ["Edin Mujagic <edinmujagic2 at gmail com>"]
edition = "2018"

[dependencies]
ajson = "0.2.0"
opener = "0.4.0"
nickel = "0.11.0"
reqwest = "0.9.20"
serde = "1.0.99"
serde_json = "1.0.40"
